package formulario;

import clases.Aeropuerto;
import clases.Avion;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import utilidades.MetodosSueltos;
import utilidades.VariablesGlobales;

/**
 *
 * @author gonza
 */
public class GestionarAviones extends javax.swing.JDialog {

    private boolean modo;

    //modo true = activar y desactivar aviones
    //modo false = eliminar
    public GestionarAviones(java.awt.Frame parent, boolean modal, boolean modo) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        agruparActivadoDesactivado.add(rdbActivado);
        agruparActivadoDesactivado.add(rdbDesactivado);
        this.modo = modo;
        MetodosSueltos.cargarAeropuertos(cmbAeropuertos);

        if (!modo) {
            rdbActivado.setVisible(false);
            rdbDesactivado.setVisible(false);
            btnGuardar.setText("Eliminar");

        } else {
            agruparActivadoDesactivado.add(rdbActivado);
            agruparActivadoDesactivado.add(rdbDesactivado);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agruparActivadoDesactivado = new javax.swing.ButtonGroup();
        aeropuertoLabel = new javax.swing.JLabel();
        avionLabel = new javax.swing.JLabel();
        rdbActivado = new javax.swing.JRadioButton();
        rdbDesactivado = new javax.swing.JRadioButton();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        estadoAvionLabel = new javax.swing.JLabel();
        cmbAeropuertos = new javax.swing.JComboBox<>();
        cmbAviones = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        aeropuertoLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        aeropuertoLabel.setText("Aeropuerto");
        aeropuertoLabel.setName("aeropuertoLabel"); // NOI18N

        avionLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        avionLabel.setText("Avion");
        avionLabel.setName("avionLabel"); // NOI18N

        agruparActivadoDesactivado.add(rdbActivado);
        rdbActivado.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rdbActivado.setSelected(true);
        rdbActivado.setText("Activado");
        rdbActivado.setName("rdbActivado"); // NOI18N

        agruparActivadoDesactivado.add(rdbDesactivado);
        rdbDesactivado.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rdbDesactivado.setText("Desactivado");
        rdbDesactivado.setName("rdbDesactivado"); // NOI18N

        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setName("btnGuardar"); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setName("btnCancelar"); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        estadoAvionLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        estadoAvionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        estadoAvionLabel.setText("INGRESE ESTADO DE UN AVION");
        estadoAvionLabel.setName("estadoAvionLabel"); // NOI18N

        cmbAeropuertos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cmbAeropuertos.setName("cmbAeropuertos"); // NOI18N
         cmbAeropuertos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbAeropuertoItemStateChanged(evt);
            }
        });

        cmbAviones.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cmbAviones.setName("cmbAviones"); // NOI18N
        cmbAviones.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbAvionesItemStateChanged(evt);
            }
        });
        cmbAviones.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbAvionesItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(estadoAvionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnGuardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCancelar)
                                .addGap(52, 52, 52))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(rdbActivado)
                                .addGap(54, 54, 54)
                                .addComponent(rdbDesactivado)
                                .addGap(158, 158, 158))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(avionLabel)
                            .addComponent(aeropuertoLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmbAviones, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbAeropuertos, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(86, 86, 86))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(estadoAvionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aeropuertoLabel)
                    .addComponent(cmbAeropuertos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(avionLabel)
                    .addComponent(cmbAviones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbActivado)
                    .addComponent(rdbDesactivado))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

  



	private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {                                           

        if (!this.modo) {
            Aeropuerto auxAero = VariablesGlobales.aeropuertos.get(this.cmbAeropuertos.getSelectedIndex());

            Avion a = auxAero.getAvion(this.cmbAviones.getSelectedItem().toString());

            auxAero.eliminarAvion(a);
            JOptionPane.showMessageDialog(this, "Se ha borrado el avion", "Info", JOptionPane.INFORMATION_MESSAGE);

            try {
                MetodosSueltos.actualizarFichero();

                this.cmbAviones.removeAllItems();

                for (Avion aux : auxAero.getAviones()) {
                    this.cmbAviones.addItem(a.getModelo());
                }

                if (auxAero.tieneAviones()) {
                    btnGuardar.setEnabled(true);
                } else {
                    btnGuardar.setEnabled(false);
                }

            } catch (IOException ex) {
                Logger.getLogger(GestionarAviones.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            Aeropuerto auxAero = VariablesGlobales.aeropuertos.get(this.cmbAeropuertos.getSelectedIndex());

            if (auxAero.tieneAviones()) {
                Avion a = auxAero.getAvion(this.cmbAviones.getSelectedItem().toString());

                if (this.rdbActivado.isSelected()) {
                    a.setActivado(true);
                    JOptionPane.showMessageDialog(this, "El avion se ha activado", "Info", JOptionPane.INFORMATION_MESSAGE);
                } else if (this.rdbDesactivado.isSelected()) {
                    a.setActivado(false);
                    JOptionPane.showMessageDialog(this, "El avion se ha desactivado", "Info", JOptionPane.INFORMATION_MESSAGE);
                }
            }

        }


    }
    

    private void cmbAeropuertoItemStateChanged(java.awt.event.ItemEvent evt) {                                               

        Aeropuerto auxAero = VariablesGlobales.aeropuertos.get(this.cmbAeropuertos.getSelectedIndex());

        if (auxAero.tieneAviones()) {

            this.cmbAviones.removeAllItems();

            for (Avion a : auxAero.getAviones()) {
                this.cmbAviones.addItem(a.getModelo());
            }

            btnGuardar.setEnabled(true);
        } else {
            btnGuardar.setEnabled(false);
        }


    }

   

    private void cmbAvionesItemStateChanged(java.awt.event.ItemEvent evt) {                                            

        Aeropuerto auxAero = VariablesGlobales.aeropuertos.get(this.cmbAeropuertos.getSelectedIndex());

        if (auxAero.tieneAviones() && this.cmbAviones.getItemCount() != 0) {
            Avion a = auxAero.getAvion(this.cmbAviones.getSelectedItem().toString());

            if (a.isActivado()) {
                this.rdbActivado.setSelected(true);
            } else {
                this.rdbDesactivado.setSelected(true);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aeropuertoLabel;
    private javax.swing.ButtonGroup agruparActivadoDesactivado;
    private javax.swing.JLabel avionLabel;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cmbAeropuertos;
    private javax.swing.JComboBox<String> cmbAviones;
    private javax.swing.JLabel estadoAvionLabel;
    private javax.swing.JRadioButton rdbActivado;
    private javax.swing.JRadioButton rdbDesactivado;
    // End of variables declaration//GEN-END:variables
}
